### ISSUE TITLE
Render markdown in TextSection

### ISSUE THREAD

**Issue by PPACI** [cheaty-sheet/Cheaty#10]
```yml
title: My Cheatsheet
description: custom description
blocks:
  - title: My first block
    sections:
      - type: text
        content: **My first** content
```
