### ISSUE TITLE
Inject or override css in options

### ISSUE THREAD

**Issue by PPACI** [cheaty-sheet/Cheaty#11]
```yml
title: NGINX
description: "test"
options:
  - style: ./style.css
  - style_override: false|true (false by default)
blocks:
  - ...
```
