### ISSUE TITLE
Create YAML parser

### ISSUE THREAD

**Issue by PPACI** [cheaty-sheet/Cheaty#4]
Provide capabilities to read sheet cheat from a YAML file.

**Comment by Nakasar** [comment]
Suggestion of YAML structure (reflect the example given in #1  ):
(without any layout, style or custom properties)

```yaml
title: 'The Title of the Cheat Sheet'
description: >-
  A small description that will appear to the left of the title (see example).
author: 'Someone'
blocks:
  - title: 'Port (listen)'
    content:
      - type: code
        language: nginx
        content: >-
          #standard HTTP protocol
          server {
            listen 80;
            listen 443 ssl;
          }
      - type: text
        content: Some text to render in the block.
```
